equipment/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    #车间信息
    path('manufacturingshop/', views.shop),
    path('add_shop/', views.addshop),
    path('edit_shop/<int:manufacturingshop_id>/', views.editshop),
    path('delete_shop/<int:manufacturingshop_id>/', views.deleteshop),
    #设备信息
    path('equipment/', views.equipment),
    path('add_equipment/', views.addequipment),
    path('edit_equipment/<int:equipment_id>/', views.editequipment),
    path('delete_equipment/<int:equipment_id>/', views.deleteequipment),
    path('newqrcode/<int:equipment_id>/', views.newqrcode),
    #车间查看设备信息
    path('manufacturingshop/<num>/', views.shopequipment),
    #巡检信息
    path('inspection/', views.inspection),
    path('add_inspection/', views.addinspection),
    path('edit_inspection/<int:inspection_id>/', views.editinspection),
    path('delete_inspection/<int:inspection_id>/', views.deleteinspection),
    #维修信息
    path('maintain/', views.maintain),
    path('add_maintain/', views.addmaintain),
    path('edit_maintain/<int:maintain_id>/', views.editmaintain),
    path('delete_maintain/<int:maintain_id>/', views.deletemaintain),
    #保养信息
    path('upkeep/', views.upkeep),
    path('add_upkeep/', views.addupkeep),
    path('edit_upkeep/<int:upkeep_id>/', views.editupkeep),
    path('delete_upkeep/<int:upkeep_id>/', views.deleteupkeep),
    #员工信息
    path('worker/', views.worker),
    path('add_worker/', views.addworker),
    path('edit_worker/<int:worker_id>/', views.editworker),
    path('delete_worker/<int:worker_id>/', views.deleteworker),

    path('dashboard/', views.dashboard),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('equipment.urls')),
    path('', include('user.urls')),
]

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('index/', views.index),
    path('login/', views.login),
    path('register/', views.register),
    path('logout/', views.logout),
    path('findpassword/', views.findpassword),
    path('captcha', include('captcha.urls')),
]

equipment/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
#车间
class ManufacturingShop(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(verbose_name='车间名称', max_length=64)
    def __str__(self):
        return "%s"%( self.name)
    class Meta:
        verbose_name = '车间信息'
        verbose_name_plural = '车间信息'
#设备信息
class Equipment(models.Model):
    equipment_status = (
        (0, '正常'),
        (1, '故障'),
        (2, '备用'),
    )
    id = models.IntegerField(primary_key=True)
    name = models.CharField(verbose_name='设备名称', max_length=64)
    specifications = models.CharField(verbose_name='规格型号', max_length=64)
    device_type = models.CharField(verbose_name='设备类型', max_length=128)
    status = models.SmallIntegerField(choices=equipment_status, default=0, verbose_name='设备状态')
    site = models.ForeignKey("ManufacturingShop", verbose_name='安装地点', max_length=64, on_delete=models.CASCADE)
    director = models.ForeignKey("Worker", verbose_name='设备管理人', max_length=64, on_delete=models.CASCADE)
    manufacturer = models.CharField(verbose_name='生产厂家', max_length=64)
    distributor = models.CharField(verbose_name='供应商', max_length=64)
    purchase_time = models.DateTimeField(verbose_name='购买时间')
    use_time = models.DateTimeField(verbose_name='启用时间')
    number = models.CharField(verbose_name='设备编号', max_length=64)
    parameter = models.TextField(verbose_name='设备参数')
    #picture = models.ImageField
    #handbook =

    def __str__(self):
        return "%s-%s-%s"%(self.name, self.specifications, self.number)
    class Meta:
        verbose_name = '设备信息'
        verbose_name_plural = '设备信息'
#巡检信息
class Inspection(models.Model):
    inspection_result_choice = (
        (0, '正常'),
        (1, '异常'),
    )
    inspection_status_choice = (
        (0, '正常运行'),
        (1, '停用'),
    )
    id = models.IntegerField(primary_key=True)
    time = models.DateTimeField(verbose_name='日期')
    name = models.ForeignKey("Equipment", verbose_name='巡检设备', on_delete=models.CASCADE)
    results = models.SmallIntegerField(choices=inspection_result_choice, default=0, verbose_name='结果')
    #picture =
    status = models.SmallIntegerField(choices=inspection_status_choice, default=0, verbose_name='设备状态')
    worker = models.ForeignKey("Worker", verbose_name='巡检人员', max_length=64, on_delete=models.CASCADE)
    def __str__(self):
        return "%s-%s"%(self.id, self.time)
    class Meta:
        verbose_name = '巡检信息'
        verbose_name_plural = '巡检信息'

#维修信息
class Maintain(models.Model):
    id = models.IntegerField(primary_key=True)
    time = models.DateTimeField(verbose_name='日期')
    name = models.ForeignKey("Equipment", verbose_name='维修设备', on_delete=models.CASCADE)
    results = models.TextField(verbose_name='维修工单')
    # picture =
    status = models.TextField(verbose_name='故障原因')
    worker = models.ForeignKey("Worker", verbose_name='维修人员', max_length=64, on_delete=models.CASCADE)
    def __str__(self):
        return "%s-%s" % (self.id, self.time)
    class Meta:
        verbose_name = '维修信息'
        verbose_name_plural = '维修信息'

#保养信息
class Upkeep(models.Model):
    id = models.IntegerField(primary_key=True)
    time = models.DateTimeField(verbose_name='日期')
    name = models.ForeignKey("Equipment", verbose_name='保养设备', on_delete=models.CASCADE)
    results = models.TextField(verbose_name='保养工单')
    # picture =
    status = models.TextField(verbose_name='保养内容')
    worker = models.ForeignKey("Worker", verbose_name='保养人员', max_length=64, on_delete=models.CASCADE)
    def __str__(self):
        return "%s-%s" % (self.id, self.time)
    class Meta:
        verbose_name = '保养信息'
        verbose_name_plural = '保养信息'
#工作人员
class Worker(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(verbose_name='姓名', max_length=64)
    number = models.CharField(verbose_name='人员编号', max_length=64)
    duty = models.CharField(verbose_name='职务', max_length=64)
    def __str__(self):
        return "%s-%s-%s" % (self.name, self.number, self.duty)
    class Meta:
        verbose_name = '工作人员信息'
        verbose_name_plural = '工作人员信息'

equipment/forms.py
from django import forms
from .models import *

from django.core.exceptions import ValidationError
#车间信息
class ManufacturingShopModelForm(forms.ModelForm):
    class Meta:
        model = ManufacturingShop
        fields = "__all__"
        widges = {



        }
#设备信息
class EquipmentModelForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = "__all__"
        widges = {

        }


#巡检信息
class InspectionModelForm(forms.ModelForm):
    class Meta:
        model = Inspection
        fields = "__all__"
        labels = {
        }
        widgets = {  # 设置每个字段的插件信息
            "id": forms.widgets.TextInput(attrs={"class": "form-control"}),
            "time": forms.widgets.DateInput(attrs={"type": "datetime"}),
        }
#维修信息
class MaintainModelForm(forms.ModelForm):
    class Meta:
        model = Maintain
        fields = "__all__"
        widgets = {

        }
#保养信息
class UpkeepModelForm(forms.ModelForm):
    class Meta:
        model = Upkeep
        fields = "__all__"
        widgets = {

        }
#人员信息
class WorkerModelForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = "__all__"
        widgets = {

        }

equipment/views.py
from django.shortcuts import render, redirect
from . import models
from . import forms
from .forms import EquipmentModelForm, InspectionModelForm, MaintainModelForm, UpkeepModelForm, WorkerModelForm, ManufacturingShopModelForm
from .models import ManufacturingShop, Equipment, Inspection, Upkeep, Maintain, Worker
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
import qrcode
from django.utils.six import BytesIO
from django.http import HttpResponse
#车间信息
def shop(request):
    #模板取数据
    ManufacturingShopList = ManufacturingShop.objects.all()
    #数据传递给模板，模板渲染页面，渲染好页面传递给浏览器
    return render(request, 'Equipment/shop/ManufacturingShop.html', {"manufacturingshops": ManufacturingShopList})
#增加车间信息
def addshop(request):
    shop_form = ManufacturingShopModelForm
    if request.method == 'POST':
        shop_form = ManufacturingShopModelForm(request.POST)
        if shop_form.is_valid():
            shop_form.save()
            message = '添加成功！'
            return redirect('/manufacturingshop/')
        else:
            return render(request, 'Equipment/shop/add_shop.html', locals())
    shop_form = forms.ManufacturingShopModelForm()
    return render(request, 'Equipment/shop/add_shop.html', locals())
#修改车间信息
def editshop(request, manufacturingshop_id):
    edit_shop = models.ManufacturingShop.objects.get(pk=manufacturingshop_id)
    shop_from = ManufacturingShopModelForm(instance=edit_shop)
    if request.method == 'POST':
        shop_from = ManufacturingShopModelForm(request.POST, instance=edit_shop)
        if shop_from.is_valid():
            shop_from.save()
            return redirect('/manufacturingshop/')
        else:
            return render(request, 'Equipment/shop/edit_shop.html', locals())
    shop_form = forms.ManufacturingShopModelForm(instance=edit_shop)
    return render(request, 'Equipment/shop/edit_shop.html', locals())
#删除车间信息
def deleteshop(request, manufacturingshop_id):
    delete_shop = models.ManufacturingShop.objects.get(id=manufacturingshop_id)
    shop_from = ManufacturingShopModelForm(instance=delete_shop)
    if request.method == 'POST':
        ManufacturingShop.objects.filter(id=manufacturingshop_id).first().delete()
        return redirect('/manufacturingshop/')
    return render(request, 'Equipment/shop/delete_shop.html', locals())

#设备信息
def equipment(request):
    EquipmentList = Equipment.objects.all()
    return render(request, 'Equipment/equipment/Equipment.html', {"equipments": EquipmentList})
#增加设备信息
def addequipment(request):
    equipment_form = EquipmentModelForm
    if request.method == 'POST':
        equipment_form = EquipmentModelForm(request.POST)
        if equipment_form.is_valid():
            equipment_form.save()
            return redirect('/equipment/')
        else:
            return render(request, 'Equipment/equipment/add_equipment.html', locals())
    equipment_form = forms.EquipmentModelForm()
    return render(request, 'Equipment/equipment/add_equipment.html', locals())
#修改设备信息
def editequipment(request, equipment_id):
    edit_equipment = models.Equipment.objects.get(pk=equipment_id)
    equipment_from = EquipmentModelForm(instance=edit_equipment)
    if request.method == 'POST':
        equipment_from = EquipmentModelForm(request.POST, instance=edit_equipment)
        if equipment_from.is_valid():
            equipment_from.save()
            return redirect('/equipment/')
        else:
            return render(request, 'Equipment/equipment/edit_equipment.html', locals())
    equipment_form = forms.EquipmentModelForm(instance=edit_equipment)
    return render(request, 'Equipment/equipment/edit_equipment.html', locals())
#删除设备信息
def deleteequipment(request, equipment_id):
    delete_equipment = models.Equipment.objects.get(pk=equipment_id)
    equipment_from = EquipmentModelForm(instance=delete_equipment)
    if request.method == 'POST':
        Equipment.objects.filter(pk=equipment_id).first().delete()
        return redirect('/equipment/')
    return render(request, 'Equipment/equipment/delete_equipment.html', locals())



def newqrcode(request, equipment_id):
    information = models.Equipment.objects.get(id=equipment_id)
    i = qrcode.make(information)
    buf = BytesIO()
    i.save(buf)
    image_stream = buf.getvalue()
    response = HttpResponse(image_stream, content_type='image/png')
    return response



#车间与设备关联
def shopequipment(request, num):
    manufacturingshop = ManufacturingShop.objects.get(pk=num)
    EquipmentList = manufacturingshop.equipment_set.all()
    return render(request, 'Equipment/equipment/Equipment.html', {"equipments": EquipmentList})

#巡检信息
def inspection(request):
    inspectionList = Inspection.objects.all()
    return render(request, 'Equipment/inspection/inspection.html', {"inspections": inspectionList})
#增加巡检信息
def addinspection(request):
    inspection_form = InspectionModelForm
    if request.method == 'POST':
        inspection_form = InspectionModelForm(request.POST)
        if inspection_form.is_valid():
            inspection_form.save()
            return redirect('/inspection/')
        else:
            return render(request, 'Equipment/inspection/new_inspection.html', locals())
    inspection_form = forms.InspectionModelForm()
    return render(request, 'Equipment/inspection/new_inspection.html', locals())
#修改巡检信息
def editinspection(request, inspection_id):
    edit_inspection = models.Inspection.objects.get(pk=inspection_id)
    inspection_from = InspectionModelForm(instance=edit_inspection)
    if request.method == 'POST':
        inspection_from = InspectionModelForm(request.POST, instance=edit_inspection)
        if inspection_from.is_valid():
            inspection_from.save()
            return redirect('/inspection/')
        else:
            return render(request, 'Equipment/inspection/edit_inspection.html', locals())
    inspection_form = forms.InspectionModelForm(instance=edit_inspection)
    return render(request, 'Equipment/inspection/edit_inspection.html', locals())
#删除巡检信息
def deleteinspection(request, inspection_id):
    delete_inspection = models.Inspection.objects.get(id=inspection_id)
    inspection_from = InspectionModelForm(instance=delete_inspection)
    if request.method == 'POST':
        Inspection.objects.filter(id=inspection_id).first().delete()
        return redirect('/inspection/')
    return render(request, 'Equipment/inspection/delete_inspection.html', locals())

#维修信息
def maintain(request):
    maintainList = Maintain.objects.all()
    return render(request, 'Equipment/maintain/maintain.html', {"maintains": maintainList})
#增加维修信息
def addmaintain(request):
    maintain_form = MaintainModelForm
    if request.method == 'POST':
        maintain_form = MaintainModelForm(request.POST)
        if maintain_form.is_valid():
            maintain_form.save()
            return redirect('/maintain/')
        else:
            return render(request, 'Equipment/maintain/add_maintain.html', locals())
    maintain_form = forms.MaintainModelForm()
    return render(request, 'Equipment/maintain/add_maintain.html', locals())
#修改维修信息
def editmaintain(request, maintain_id):
    edit_maintain = models.Maintain.objects.get(pk=maintain_id)
    maintain_from = MaintainModelForm(instance=edit_maintain)
    if request.method == 'POST':
        maintain_from = MaintainModelForm(request.POST, instance=edit_maintain)
        if maintain_from.is_valid():
            maintain_from.save()
            return redirect('/maintain/')
        else:
            return render(request, 'Equipment/maintain/edit_maintain.html', locals())
    maintain_form = forms.MaintainModelForm(instance=edit_maintain)
    return render(request, 'Equipment/maintain/edit_maintain.html', locals())
#删除维修信息
def deletemaintain(request, maintain_id):
    delete_maintain = models.Maintain.objects.get(id=maintain_id)
    maintain_from = MaintainModelForm(instance=delete_maintain)
    if request.method == 'POST':
        Maintain.objects.filter(id=maintain_id).first().delete()
        return redirect('/maintain/')
    return render(request, 'Equipment/maintain/delete_maintain.html', locals())


#保养信息
def upkeep(request):
    upkeepList = Upkeep.objects.all()
    return render(request, 'Equipment/upkeep/upkeep.html', {"upkeeps": upkeepList})
#增加保养信息
def addupkeep(request):
    upkeep_form = UpkeepModelForm
    if request.method == 'POST':
        upkeep_form = UpkeepModelForm(request.POST)
        if upkeep_form.is_valid():
            upkeep_form.save()
            return redirect('/upkeep/')
        else:
            return render(request, 'Equipment/upkeep/add_upkeep.html', locals())
    upkeep_form = forms.UpkeepModelForm()
    return render(request, 'Equipment/upkeep/add_upkeep.html', locals())
#修改保养信息
def editupkeep(request, upkeep_id):
    edit_upkeep = models.Upkeep.objects.get(pk=upkeep_id)
    upkeep_from = UpkeepModelForm(instance=edit_upkeep)
    if request.method == 'POST':
        upkeep_from = UpkeepModelForm(request.POST, instance=edit_upkeep)
        if upkeep_from.is_valid():
            upkeep_from.save()
            return redirect('/upkeep/')
        else:
            return render(request, 'Equipment/upkeep/edit_upkeep.html', locals())
    upkeep_form = forms.UpkeepModelForm(instance=edit_upkeep)
    return render(request, 'Equipment/upkeep/edit_upkeep.html', locals())
#删除保养信息
def deleteupkeep(request, upkeep_id):
    delete_upkeep = models.Upkeep.objects.get(id=upkeep_id)
    upkeep_from = UpkeepModelForm(instance=delete_upkeep)
    if request.method == 'POST':
        Upkeep.objects.filter(id=upkeep_id).first().delete()
        return redirect('/upkeep/')
    return render(request, 'Equipment/upkeep/delete_upkeep.html', locals())

#人员信息
def worker(request):
    workerList = Worker.objects.all()
    return render(request, 'Equipment/worker/worker.html', {"workers": workerList})
#增加人员信息
def addworker(request):
    worker_form = WorkerModelForm

templates/Equipment/inspection/delete_inspection.html
{% extends 'base.html' %}
{% load static %}
{% block title %}删除巡检信息{% endblock %}
{% block css %}

  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        删除巡检信息
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li>巡检信息</li>
        <li class="active">删除巡检信息</li>
      </ol>
    </section>


    <div class="container">
        <div class="col-md-offset-4 col-md-4">
            <form class="form-register" method="post">
                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
                {% csrf_token %}

                <h2 class="text-center">删除巡检信息</h2>

                <div class="form-group">
                    {{ inspection_from.id.label_tag }}
                    {{inspection_from.id }}
                </div>
                <div class="form-group">
                    {{ inspection_from.time.label_tag }}
                    {{ inspection_from.time }}
                </div>
                <div class="form-group">
                    {{ inspection_from.name.label_tag }}
                    {{ inspection_from.name }}
                </div>
                <div class="form-group">
                    {{ inspection_from.results.label_tag }}
                    {{ inspection_from.results }}
                </div>
                <div class="form-group">
                    {{ inspection_from.status.label_tag }}
                    {{ inspection_from.status}}
                </div>
                <div class="form-group">
                    {{ inspection_from.worker.label_tag }}
                    {{ inspection_from.worker }}
                </div>
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">删除</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/Equipment/inspection/edit_inspection.html
{% extends 'base.html' %}
{% load static %}
{% block title %}修改巡检信息{% endblock %}
{% block css %}

  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        修改巡检信息
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li>巡检信息</li>
        <li class="active">修改巡检信息</li>
      </ol>
    </section>


    <div class="container">
        <div class="col-md-offset-4 col-md-4">
            <form class="form-register"  method="post">
                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
                {% csrf_token %}

                <h2 class="text-center">修改巡检信息</h2>

                <div class="form-group">
                    {{ inspection_from.id.label_tag }}
                    {{ inspection_from.id }}
                </div>
                <div class="form-group">

                    {{ inspection_from.time.label_tag }}
                    {{ inspection_from.time }}
                </div>
                <div class="form-group">
                    {{ inspection_from.name.label_tag }}
                    {{ inspection_from.name }}
                </div>
                <div class="form-group">
                    {{ inspection_from.results.label_tag }}
                    {{ inspection_from.results }}
                </div>
                <div class="form-group">
                    {{ inspection_from.status.label_tag }}
                    {{ inspection_from.status}}
                </div>
                <div class="form-group">
                    {{ inspection_from.worker.label_tag }}
                    {{ inspection_from.worker }}
                </div>
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/Equipment/inspection/inspection.html
{% extends 'base.html' %}
{% load static %}
{% block title %}巡检信息{% endblock %}

{% block css %}
     <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        巡检信息
        <small>assets list</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">巡检信息</li>
      </ol>
    </section>
{% endblock %}

{% block content %}

   <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

        <div class="box">
        <div class="box-header">
          <h3 class="box-title">巡检信息<small></small></h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <a href="/add_inspection/" title="添加"><i class="glyphicon glyphicon-plus"></i></a>
            <table id="assets_table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>日期</th>
                        <th>巡检设备</th>
                        <th>结果</th>
                        <th>设备状态</th>
                        <th>巡检人员</th>
                    </tr>
                </thead>
                <tbody>

                {% for inspection in inspections %}

                    <tr>
                        <td>{{ forloop.counter }}</td>

                        <td>{{ inspection.time|date:"Y/m/d [H:m:s]" }}</td>

                        <td>{{ inspection.name }}</td>

                        <td>{{ inspection.get_results_display }}</td>

                        <td>{{ inspection.get_status_display }}</td>

                        <td>{{ inspection.worker }}</td>


                        <td>
                            <a href="/edit_inspection/{{ inspection.id }}" title="修改"><i class="glyphicon glyphicon-pencil"></i></a>
                            <a href="/delete_inspection/{{ inspection.id }}" onclick="return delete_data()" title="删除"><i class="glyphicon glyphicon-trash text-danger"></i></a>
                        </td>


                    </tr>

                {% empty %}
                <tr>没有数据</tr>
                {% endfor %}

                </tbody>
                <tfoot>
                    <tr>
                         <th>序号</th>
                        <th>日期</th>
                        <th>巡检设备</th>
                        <th>结果</th>
                        <th>设备状态</th>
                        <th>巡检人员</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
        </div>
    <!-- /.col -->
      </div>
    <!-- /.row -->
    </section>

{% endblock %}

{% block script %}

<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>

<script>

$(function () {
        $('#assets_table').DataTable({
          "paging": true,       <!-- 允许分页 -->
          "lengthChange": true, <!-- 允许改变每页显示的行数 -->
          "searching": true,    <!-- 允许内容搜索 -->
          "ordering": true,     <!-- 允许排序 -->
          "info": true,         <!-- 显示信息 -->
          "autoWidth": false    <!-- 固定宽度 -->
        });
      });

</script>

{% endblock %}

templates/Equipment/inspection/new_inspection.html
{% extends 'base.html' %}
{% load static %}
{% block title %}添加巡检信息{% endblock %}
{% block css %}

  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        添加巡检信息
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li>巡检信息</li>
        <li class="active">添加巡检信息</li>
      </ol>
    </section>


    <div class="container">
        <div class="col-md-offset-4 col-md-4">
            <form class="form-register" action="/add_inspection/" method="post">
                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
                {% csrf_token %}

                <h2 class="text-center">添加巡检信息</h2>

                <div class="form-group">
                    {{ inspection_form.id.label_tag }}
                    {{ inspection_form.id }}
                </div>
                <div class="form-group">
                    {{ inspection_form.time.label_tag }}
                    {{ inspection_form.time }}
                </div>
                <div class="form-group">
                    {{ inspection_form.name.label_tag }}
                    {{ inspection_form.name }}
                </div>
                <div class="form-group">
                    {{ inspection_form.results.label_tag }}
                    {{ inspection_form.results }}
                </div>
                <div class="form-group">
                    {{ inspection_form.status.label_tag }}
                    {{ inspection_form.status}}
                </div>
                <div class="form-group">
                    {{ inspection_form.worker.label_tag }}
                    {{ inspection_form.worker }}
                </div>
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div>

{% endblock %}